### ISSUE TITLE
Replace Lorem Ipsum with content

### ISSUE THREAD

**Issue by DanielSchetritt** [csun-metalab/decathlon#1]
# Details
There is some filler text on every page except `/front-end.html`. 
# Todo
- [ ] Add content to `/design.html`.
- [ ] Add content to `/back-end.html`.
- [ ] Add content to `/operations.html`.

**Comment by DanielSchetritt** [comment]
Perhaps we should split this into multiple issues.
